### ISSUE TITLE
[Docker] 确定 container_id 生产方式， 确实是不是全球唯一

### ISSUE THREAD

**Issue by xcluo** [THSTACK/bug-report#26]

**Comment by longgeek** [comment]
测试两台机器使用相同镜像、名字、命令所得 id 不同。


Because according to calculations like this:
http://en.wikipedia.org/wiki/Universally_unique_identifier#Random_UUID_probability_of_duplicates

The approximate chance of 100 million containers having an ID collision with the current completely random 256bit id is 1-e^(-(10^8)/(2*2^(256)) which is about 4.318*10^-70. That seems quite unlikely. Of course, the random numbers are not perfectly random, but I don't expect it to be vastly different than that.

**Comment by xcluo** [comment]
是基本上不可能，他们自己也承认， 有可能，但很小。 4.31810^-70 ，是很小。    有没有自定义container_id 配置的地方？
